
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jun 29 12:41:57 UYT 2014
//----------------------------------------------------

package com.language.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int INTEGRAL = 58;
  public static final int ESCAPE = 14;
  public static final int PARSE_FUNCT = 55;
  public static final int TO_LOWER_CASE_FUNCT = 42;
  public static final int INCREMENT = 20;
  public static final int BLOCK_BEGIN = 33;
  public static final int ASSIGNMENT = 19;
  public static final int REVERSE_FUNCT = 52;
  public static final int SPLIT_FUNCT = 47;
  public static final int NOT_EQUAL = 32;
  public static final int CONTINUE = 38;
  public static final int RIGHT_SQUARE_BRACKETS = 10;
  public static final int GREATER = 27;
  public static final int TO_UPPER_CASE_FUNCT = 41;
  public static final int FOR = 36;
  public static final int LESS = 28;
  public static final int DECREMENT = 21;
  public static final int LENGTH_FUNCT = 39;
  public static final int NOT = 26;
  public static final int SEMICOLON = 3;
  public static final int AND = 24;
  public static final int LAST_INDEX_OF_FUNCT = 45;
  public static final int OR = 25;
  public static final int COMMA = 4;
  public static final int TABULATION = 13;
  public static final int RIGHT_ROUND_BRACKETS = 6;
  public static final int LESS_EQUAL = 30;
  public static final int SUBTRACTION = 16;
  public static final int IF = 34;
  public static final int ID = 57;
  public static final int POP_FUNCT = 49;
  public static final int PUSH_FUNCT = 50;
  public static final int DECIMAL = 59;
  public static final int EOF = 0;
  public static final int DOUBLE_QUOTE = 7;
  public static final int EQUAL = 31;
  public static final int TRUE = 22;
  public static final int GREATER_EQUAL = 29;
  public static final int error = 1;
  public static final int BREAK = 37;
  public static final int CONCAT_FUNCT = 40;
  public static final int SINGLE_QUOTE = 8;
  public static final int LEFT_SQUARE_BRACKETS = 9;
  public static final int ELSE = 35;
  public static final int POINT = 2;
  public static final int INDEX_OF_FUNCT = 44;
  public static final int LINE_BREAK = 12;
  public static final int ADDITION = 15;
  public static final int LEFT_ROUND_BRACKETS = 5;
  public static final int SUBSTRING_FUNCT = 46;
  public static final int STRING = 56;
  public static final int IS_NAN = 54;
  public static final int JOIN_FUNCT = 48;
  public static final int FALSE = 23;
  public static final int DIVISION = 18;
  public static final int NAN = 53;
  public static final int CHAR_AT_FUNCT = 43;
  public static final int VAR = 11;
  public static final int MULTIPLICATION = 17;
  public static final int SHIFT_FUNCT = 51;
}

