
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jul 13 19:17:15 UYT 2014
//----------------------------------------------------

package com.language.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int INTEGRAL = 69;
  public static final int ESCAPE = 19;
  public static final int PARSE_FUNCT = 66;
  public static final int FUNCTION = 15;
  public static final int TO_LOWER_CASE_FUNCT = 52;
  public static final int INCREMENT = 27;
  public static final int BLOCK_BEGIN = 40;
  public static final int REVERSE_FUNCT = 63;
  public static final int RIGHT_SQUARE_BRACKET = 11;
  public static final int SPLIT_FUNCT = 57;
  public static final int BLOCK_END = 41;
  public static final int NOT_EQUAL = 39;
  public static final int CONTINUE = 47;
  public static final int GREATER = 34;
  public static final int TO_UPPER_CASE_FUNCT = 51;
  public static final int FOR = 45;
  public static final int LESS = 35;
  public static final int MINUS = 21;
  public static final int DECREMENT = 28;
  public static final int LENGTH_FUNCT = 48;
  public static final int NOT = 33;
  public static final int SEMICOLON = 4;
  public static final int AND = 31;
  public static final int LAST_INDEX_OF_FUNCT = 55;
  public static final int OR = 32;
  public static final int COMMA = 5;
  public static final int TABULATION = 18;
  public static final int DIV = 23;
  public static final int LESS_EQUAL = 37;
  public static final int PLUS = 20;
  public static final int IF = 43;
  public static final int ID = 68;
  public static final int POP_FUNCT = 60;
  public static final int TYPEOF_FUNCT = 50;
  public static final int PUSH_FUNCT = 61;
  public static final int LEFT_ROUND_BRACKET = 6;
  public static final int DECIMAL = 70;
  public static final int EOF = 0;
  public static final int DOUBLE_QUOTE = 8;
  public static final int RETURN = 14;
  public static final int EQUAL = 24;
  public static final int GREATER_EQUAL = 36;
  public static final int TRUE = 29;
  public static final int LEFT_SQUARE_BRACKET = 10;
  public static final int NEW = 13;
  public static final int error = 1;
  public static final int NULL = 2;
  public static final int CONSOLE_LOG = 59;
  public static final int BREAK = 46;
  public static final int CONCAT_FUNCT = 49;
  public static final int SINGLE_QUOTE = 9;
  public static final int TIMES = 22;
  public static final int COLON = 26;
  public static final int ELSE = 42;
  public static final int POINT = 3;
  public static final int INDEX_OF_FUNCT = 54;
  public static final int WHILE = 44;
  public static final int QUEST = 25;
  public static final int ALERT = 16;
  public static final int LINE_BREAK = 17;
  public static final int SUBSTRING_FUNCT = 56;
  public static final int STRING = 67;
  public static final int IS_NAN = 65;
  public static final int JOIN_FUNCT = 58;
  public static final int FALSE = 30;
  public static final int NAN = 64;
  public static final int CHAR_AT_FUNCT = 53;
  public static final int VAR = 12;
  public static final int SHIFT_FUNCT = 62;
  public static final int EQUAL_EQUAL = 38;
  public static final int RIGHT_ROUND_BRACKET = 7;
}

